### ISSUE TITLE
```SwitchDoesNotHandleAllEnumOptions``` with a ```default``` in my switch. Should I ignore SS018 ?

### ISSUE THREAD

**Issue by jmguazzo** [Vannevelj/SharpSource#325]
When I have a switch that handles certains enum values with a ```default:```, should I ignore SS018 or should the analyzer not raise it ?

ex : 
```
public enum FizzBuzz
{
    None = 0,
    Fizz = 1,
    Buzz = 2,
    FizzBuzz = 3
}
```
```
FizzBuzz fz = FizzBuzz.None;
switch (fz) //SS018 raised here
{
    case FizzBuzz.FizzBuzz:
          doFizzBuzz();
          break;
    case FizzBuzz.Buzz:
          doBuzz();
          break;
    default: 
          doDefault();
          break;
}
```

**Comment by Vannevelj** [comment]
That's a good question. Up until now the design has been to deliberately trigger the analyzer but I can see the argument for the opposite as well.

Perhaps the existence of `default` is an indication that we explicitly don't want to handle each option, and as such the analyzer shouldn't raise a warning.
My only concern is that we'll hide potential issues if the enum is changed to contain new values and they'll now be handled by the `default` block. Which, in turn, is of course the entire reason why `default` exists in the first place.

Another alternative is to change the code fix to output the enum statement as the same branch as `default` instead of giving it its own:

```cs
FizzBuzz fz = FizzBuzz.None;
switch (fz) //SS018 raised here
{
    case FizzBuzz.FizzBuzz:
          doFizzBuzz();
          break;
    case FizzBuzz.Buzz:
          doBuzz();
          break;
	case FizzBuzz.Fizz:
    default: 
          doDefault();
          break;
}
```

What would you expect the behaviour to be?

**Comment by jmguazzo** [comment]
I think that if a default is there, it should raise a message with the type "information".
The "warning" should only be used when there's no default.

I'm not a huge fan of specifying each case before default because it can overload the code when you only need specific action on a few values of an enum but generic action for all the others. 

And specifying a lot of empty cases before a default might go against the principle of least astonishment, if I specify all the cases, I don't need a default.

**Comment by Vannevelj** [comment]
That makes sense 👍 an update will be available in a few minutes once https://github.com/Vannevelj/SharpSource/pull/327 is merged
